# Generated by Django 5.2.3 on 2025-06-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('vendor', 'Vendor'), ('customer', 'Customer')], max_length=10, null=True),
        ),
    ]
